language: go

go:    
    - 1.7
    - tip

before_install:
    - sudo apt-get install -qq libpcap-dev
    - go get github.com/jteeuwen/go-bindata
    - go install github.com/jteeuwen/go-bindata/go-bindata

install:
     - go get -d -t -v ./...
     - ./build.sh -it kateway
     - ./build.sh -it gk
     - ./build.sh -it actord
     - ./build.sh -it ehaproxy
     - ./build.sh -it kguard

test:
    - cd cmd; go vet ./...
    - go test github.com/funkygao/gafka/cmd/kateway/gateway
    - cd cmd; go test ./...

# this should give us faster builds according to 
# http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false
